{
  "error": "(InternalError) DefaultAzureCredential failed to retrieve a token from the included credentials.\nAttempted credentials:\n\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\nVisit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\n\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\n\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\n\tAzureCliCredential: ERROR: The command failed with an unexpected error. Here is the traceback:\nERROR: Can't get attribute 'NormalizedResponse' on <module 'msal.throttled_http_client' from 'C:\\\\Program Files\\\\Microsoft SDKs\\\\Azure\\\\CLI2\\\\Lib\\\\site-packages\\\\msal\\\\throttled_http_client.pyc'>\nTraceback (most recent call last):\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\knack/cli.py\", line 233, in invoke\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py\", line 666, in execute\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py\", line 734, in _run_jobs_serially\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py\", line 703, in _run_job\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py\", line 336, in __call__\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/command_operation.py\", line 120, in handler\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/command_modules/profile/custom.py\", line 83, in get_access_token\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/_profile.py\", line 478, in get_raw_token\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/_profile.py\", line 691, in _create_credential\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/auth/identity.py\", line 248, in get_user_credential\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/auth/identity.py\", line 118, in _msal_public_app_kwargs\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/auth/identity.py\", line 103, in _msal_app_kwargs\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/auth/identity.py\", line 136, in _load_msal_http_cache\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/auth/binary_cache.py\", line 28, in __init__\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/auth/binary_cache.py\", line 44, in load\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/decorators.py\", line 102, in _wrapped_func\n  File \"D:\\a\\_work\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/auth/binary_cache.py\", line 35, in _load\nAttributeError: Can't get attribute 'NormalizedResponse' on <module 'msal.throttled_http_client' from 'C:\\\\Program Files\\\\Microsoft SDKs\\\\Azure\\\\CLI2\\\\Lib\\\\site-packages\\\\msal\\\\throttled_http_client.pyc'>. Did you mean: '_msal_public_app_kwargs'?\nTo check existing issues, please visit: https://github.com/Azure/azure-cli/issues\n\n\tAzurePowerShellCredential: Please run \"Connect-AzAccount\" to set up account\n\tAzureDeveloperCliCredential: {\"type\":\"consoleMessage\",\"timestamp\":\"2025-07-20T13:48:51.2673739-04:00\",\"data\":{\"message\":\"\\nERROR: resolving the Azure Directory from system environment (AZURE_SUBSCRIPTION_ID): resolving user access to subscription 'ff38e682-afe0-4ec2-8e18-d14de894978f' : reauthentication required, run `azd auth login --scope https://management.azure.com//.default` to log in\\n\"}}\n\nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.",
  "tenant_id": "16b3c013-d300-468d-ac64-7eda0820b6d3",
  "project_name": "kd-foundry-project",
  "subscription_id": "ff38e682-afe0-4ec2-8e18-d14de894978f",
  "resource_group": "kd-eastus2-rg",
  "timestamp": 1753033731.2906551
}